name: kodecamp-app CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lahteeph/kodecamp-app:latest

      - name: Build and Push Docker Image
        run: |
          docker build -t lahteeph/kodecamp-app:latest .
          docker push lahteeph/kodecamp-app:latest

      - name: SSH-setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Minikube Deployment
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          kubectl config use-context minikube && 
          kubectl apply -f ./k8s/deployment.yaml &&
          kubectl apply -f ./k8s/service.yaml
          EOF

